export {default as BannerStyles} from './Banner.json'
export {default as AboutStyles} from './About.json'
export {default as SkillsContentStyles} from './SkillsContentStyles.json'
export {default as ProjectStyles} from './ProjectStyles.json'
export {default as SchoolStyles} from './SchoolsStyles.json'
export {default as FooterStyles} from './FooterStyles.json'