export {default as Banner} from './Banner'
export {default as About} from './About'
export {default as Skills} from './Skills'
export {default as Projects} from './Projects'
export {default as Schools} from './Schools'
export {default as Footer} from './Footer'